src/Entity/Annoucement.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\AnnoucementRepository;
use Doctrine\Common\Collections\Collection;
use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=AnnoucementRepository::class)
 */
#[ApiResource]
class Annoucement
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $company_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $sector;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $salary;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $contract_type;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\ManyToMany(targetEntity=Tags::class, inversedBy="annoucements")
     */
    private $tags;

    /**
     * @ORM\Column(type="datetime_immutable")
     * @Assert\DateTime
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime_immutable")
     * @Assert\DateTime
     */
    private $updated_at;

    public function __construct()
    {
        $this->tags = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getCompanyName(): ?string
    {
        return $this->company_name;
    }

    public function setCompanyName(string $company_name): self
    {
        $this->company_name = $company_name;

        return $this;
    }

    public function getSector(): ?string
    {
        return $this->sector;
    }

    public function setSector(string $sector): self
    {
        $this->sector = $sector;

        return $this;
    }

    public function getSalary(): ?string
    {
        return $this->salary;
    }

    public function setSalary(string $salary): self
    {
        $this->salary = $salary;

        return $this;
    }

    public function getContractType(): ?string
    {
        return $this->contract_type;
    }

    public function setContractType(string $contract_type): self
    {
        $this->contract_type = $contract_type;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection|Tags[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tags $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tags $tag): self
    {
        $this->tags->removeElement($tag);

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }
}

src/Form/AnnoucementType.php
<?php

namespace App\Form;


use App\Entity\Tags;
use App\Entity\Annoucement;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;

class AnnoucementType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class, [
                'required' => true,
                'label' => "Titre de l'annonce",
                'attr' => [
                    'placeholder' => "Intitulé du poste ..."
                ]
            ] )
            ->add('sector', TextType::class, [
                'required' => true, 
                'label' => "Localisation",
                'attr' => [
                    'placeholder' => "PARIS (75)..."
                ]
            ])
            ->add('salary',TextType::class, [
                'required' => true,
                'label' => "Salaire", 
                'attr' => [
                    'placeholder' => "33000 annuel"
                ]
            ])
            ->add('contract_type', ChoiceType::class, [
                'choices'  => [
                    'stage' => "STAGE",
                    'apprentissage' => "APPRENTISSAGE",
                    'professionnalisation' => "PROFESSIONNALISATION",
                ]])
            ->add('description',TextType::class, [
                'required' => true, 
                'attr' => [
                    'placeholder' => "Description du poste proposé"
                ]
            ])
            ->add('tags', EntityType::class, [
                'class' => Tags::class,
                'choice_label' => 'name',
                'multiple' => true,
                'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('t')
                    ->orderBy('t.name', 'ASC');
                }
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Annoucement::class,
        ]);
    }
}

src/Controller/AnnoucementController.php
<?php

namespace App\Controller;

use App\Entity\Annoucement;
use App\Form\AnnoucementType;
use App\Repository\AnnoucementRepository;
use DateTime;
use DateTimeImmutable;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/annoucement')]
class AnnoucementController extends AbstractController
{
    #[Route('/', name: 'annoucement_index', methods: ['GET'])]
    public function index(AnnoucementRepository $annoucementRepository): Response
    {
        return $this->render('annoucement/index.html.twig', [
            'annoucements' => $annoucementRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'annoucement_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $annoucement = new Annoucement();
        $form = $this->createForm(AnnoucementType::class, $annoucement);
        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid()) {
            $annoucement->setCompanyName($this->getUser()->getCompanyName());
            $annoucement->setCreatedAt(new DateTimeImmutable());
            $annoucement->setUpdatedAt(new DateTimeImmutable());
            dd($annoucement);
            $entityManager->persist($annoucement);
            $entityManager->flush();

            return $this->redirectToRoute('annoucement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('annoucement/new.html.twig', [
            'annoucement' => $annoucement,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'annoucement_show', methods: ['GET'])]
    public function show(Annoucement $annoucement): Response
    {
        return $this->render('annoucement/show.html.twig', [
            'annoucement' => $annoucement,
        ]);
    }

    #[Route('/{id}/edit', name: 'annoucement_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Annoucement $annoucement, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(AnnoucementType::class, $annoucement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $annoucement->setCompanyName($this->getUser()->getCompanyName());
            $annoucement->setCreatedAt(new DateTimeImmutable());
            $annoucement->setUpdatedAt(new DateTimeImmutable());
            dd($annoucement);
            //$entityManager->persist($annoucement);
            //$entityManager->flush();

            return $this->redirectToRoute('annoucement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('annoucement/edit.html.twig', [
            'annoucement' => $annoucement,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'annoucement_delete', methods: ['POST'])]
    public function delete(Request $request, Annoucement $annoucement, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$annoucement->getId(), $request->request->get('_token'))) {
            $entityManager->remove($annoucement);
            $entityManager->flush();
        }

        return $this->redirectToRoute('annoucement_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/annoucement/_delete_form.html.twig
<form method="post" action="{{ path('annoucement_delete', {'id': annoucement.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ annoucement.id) }}">
    <button class="btn">Delete</button>
</form>

templates/annoucement/_form.html.twig
{{ form_start(form) }}
     <div class="my-custom-class-for-errors">
        {{ form_errors(form) }}
    </div>

    <div class="row">
        <div class="col-md-12">
            {{ form_row(form.title) }}
        </div>
        <div class="col-md-4" id="some-custom-id">
            {{ form_row(form.sector) }}
        </div>
         <div class="col-md-4" id="some-custom-id">
            {{ form_row(form.salary) }}
        </div>
         <div class="col-md-4" id="some-custom-id">
            {{ form_row(form.contract_type) }}
        </div>
         <div class="col-md-12" id="some-custom-id">
            {{ form_row(form.description) }}
        </div>
         <div class="col-md-12" id="some-custom-id">
            {{ form_row(form.tags) }}
        </div>
    </div>
    <button class="btn btn-primary">{{ button_label|default("Ajouter l'offre") }}</button>
{{ form_end(form) }}

templates/annoucement/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Annoucement{% endblock %}

{% block body %}
    <h1>Edit Annoucement</h1>

    {{ include('annoucement/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('annoucement_index') }}">back to list</a>

    {{ include('annoucement/_delete_form.html.twig') }}
{% endblock %}

templates/annoucement/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Annoucement index{% endblock %}

{% block body %}
    <h1>Annoucement index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Company_name</th>
                <th>Sector</th>
                <th>Salary</th>
                <th>Contract_type</th>
                <th>Description</th>
                <th>Created_at</th>
                <th>Updated_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for annoucement in annoucements %}
            <tr>
                <td>{{ annoucement.id }}</td>
                <td>{{ annoucement.title }}</td>
                <td>{{ annoucement.companyName }}</td>
                <td>{{ annoucement.sector }}</td>
                <td>{{ annoucement.salary }}</td>
                <td>{{ annoucement.contractType }}</td>
                <td>{{ annoucement.description }}</td>
                <td>{{ annoucement.createdAt ? annoucement.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ annoucement.updatedAt ? annoucement.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('annoucement_show', {'id': annoucement.id}) }}">show</a>
                    <a href="{{ path('annoucement_edit', {'id': annoucement.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('annoucement_new') }}">Create new</a>
{% endblock %}

templates/annoucement/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Rédigée une offre {% endblock %}

{% block body %}
    <div class="container mt-5">
        <h1>Rédigée une offre </h1>
        {{ include('annoucement/_form.html.twig') }}
    </div>
{% endblock %}

templates/annoucement/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Annoucement{% endblock %}

{% block body %}
    <h1>Annoucement</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ annoucement.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ annoucement.title }}</td>
            </tr>
            <tr>
                <th>Company_name</th>
                <td>{{ annoucement.companyName }}</td>
            </tr>
            <tr>
                <th>Sector</th>
                <td>{{ annoucement.sector }}</td>
            </tr>
            <tr>
                <th>Salary</th>
                <td>{{ annoucement.salary }}</td>
            </tr>
            <tr>
                <th>Contract_type</th>
                <td>{{ annoucement.contractType }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ annoucement.description }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ annoucement.createdAt ? annoucement.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Updated_at</th>
                <td>{{ annoucement.updatedAt ? annoucement.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('annoucement_index') }}">back to list</a>

    <a href="{{ path('annoucement_edit', {'id': annoucement.id}) }}">edit</a>

    {{ include('annoucement/_delete_form.html.twig') }}
{% endblock %}